Controllers/MainController.cs
﻿using FullMessagePostingApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace FullMessagePostingApp.Controllers {
    
    [ApiController]
    [Route("api")]
    public class MainController : ControllerBase {
        private readonly MessagesService messagesService;
        private readonly TriviaService triviaService;

        public MainController(MessagesService messagesService, TriviaService triviaService) {
            this.messagesService = messagesService;
            this.triviaService = triviaService;
        }

        [HttpGet("json-msg")]
        //GET /api/json-msg
        public IActionResult GetJsonMessages() {
            return new JsonResult(messagesService.GetMessages());
        }
        
        [HttpGet("json-resultados")]
        //GET /api/json-resultados
        public IActionResult GetJsonResultados() {
            return new JsonResult(triviaService.TriviaResultsBoard);
        }
        
        [HttpGet("iot-msg")]
        //GET /api/json-msg
        public ContentResult GetIoTMessages() {
            return new ContentResult() {
                Content = messagesService.GetIoTMessages()
            };
        }
    }
}

Pages/Admin.cshtml.cs
﻿using System.ComponentModel.DataAnnotations;
using FullMessagePostingApp.Model;
using FullMessagePostingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FullMessagePostingApp.Pages {
    public class AdminModel : PageModel {

        private readonly MessagesService messagesService;
        private readonly TriviaService triviaService;

        public AdminModel(MessagesService messagesService, TriviaService triviaService) {
            this.messagesService = messagesService;
            this.triviaService = triviaService;
        }
        
        public IActionResult OnGet() {
            return Page();
        }

        public IActionResult OnPostCleanMessages() {
            messagesService.CleanMessages();
            return Page();
        }
        
        public IActionResult OnPostResetTrivia() {
            triviaService.ResetTrivia();
            return Page();
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FullMessagePostingApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
﻿using System.ComponentModel.DataAnnotations;
using FullMessagePostingApp.Model;
using FullMessagePostingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FullMessagePostingApp.Pages {
    public class IndexModel : PageModel {

        private readonly MessagesService messagesService;
        
        [BindProperty]
        [Required(ErrorMessage = "Name is required")]
        [StringLength(16, MinimumLength = 3)]
        public string Name { get; set; }
        
        [BindProperty]
        [Required(ErrorMessage = "Message is required")]
        [StringLength(16, MinimumLength = 3)]
        public string Message { get; set; }

        public IndexModel(MessagesService _messagesService) {
            this.messagesService = _messagesService;
        }
        
        public IActionResult OnGet() {
            return Page();
        }

        public IActionResult OnPost() {
            if (!ModelState.IsValid) {
                return Page();
            }

            var msg = new Message {
                Name = Name,
                Msg = Message
            };
            
            messagesService.AddMessage(msg);
            
            return Page();
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FullMessagePostingApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Resultados.cshtml.cs
﻿using System.ComponentModel.DataAnnotations;
using FullMessagePostingApp.Model;
using FullMessagePostingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FullMessagePostingApp.Pages {
    public class ResultadosModel : PageModel {
        
        public ResultadosModel() {
            
        }
        
        public IActionResult OnGet() {
            return Page();
        }
    }
}

Pages/Trivia.cshtml.cs
﻿using System.Collections.Generic;
 using System.ComponentModel.DataAnnotations;
 using System.Linq;
 using FullMessagePostingApp.Model;
using FullMessagePostingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FullMessagePostingApp.Pages {
    public class TriviaModel : PageModel {
        
        public string ErrorMessage { get; set; }
        public IList<TriviaItem> TriviaItems { get; set; }
        private readonly TriviaService triviaService;

        [BindProperty]
        public string Equipo { get; set; }
        
        [BindProperty]
        public List<Response> Responses { get; set; }
        
        public TriviaModel(TriviaService triviaService) {
            this.triviaService = triviaService;
            TriviaItems = triviaService.TriviaItems;
        }
        
        public IActionResult OnGet() {
            return Page();
        }

        public IActionResult OnPost() {
            if (string.IsNullOrEmpty(Equipo) || Equipo.Equals("-1")) {
                ErrorMessage = "Selecciona un Equipo";
                return Page();
            }

            var firstFoundEmptyTriviaItem = Responses.FirstOrDefault(i => i.Answer == -1);
            if (firstFoundEmptyTriviaItem != null) {
                ErrorMessage = "Debes seleccionar una respuesta para todas las preguntas";
                return Page();
            }
            
            triviaService.AddTriviaResponseFromTeam(Responses, Equipo);

            return RedirectToPage("Resultados");
        }
    }
}

Pages/Admin.cshtml
@page
@model AdminModel
@{
    ViewData["Title"] = "John Deere Day";
}
@section Scripts {

}
@section Styles {
  
}


<div class="row">
    <div class="col-lg-6 text-center">
        <img src="images/JDLogo.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
    
    <div class="col-lg-6 text-center">
            <img src="images/ITS.png" width="300px" class="img-fluid" alt="Responsive image">
        </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <h1>John Deere Day - ITS - Admin Control Panel</h1>
        <form method="post">
            <br>
            <button type="submit" asp-page-handler="CleanMessages" class="btn btn-primary">CleanMessages</button><br><br>
            <button type="submit" asp-page-handler="ResetTrivia" class="btn btn-primary">ResetTrivia</button><br>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "John Deere Day";
}
@section Scripts {
    <script src="js/index.js"></script>
}
@section Styles {
    <link rel="stylesheet" href="css/index.css"/>
}


<div class="row">
    <div class="col-lg-6 text-center">
        <img src="images/JDLogo.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
    
    <div class="col-lg-6 text-center">
            <img src="images/ITS.png" width="300px" class="img-fluid" alt="Responsive image">
        </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <h1>John Deere Day - ITS</h1>
        <form method="post">
            <div class="form-group">
                <label for="Name">Name</label>
                <input type="text" class="form-control" id="Name" name="Name" aria-describedby="emailHelp" placeholder="Your name">
                <small class="form-text text-muted">16 characters max. No Special Characters</small>
            </div>
            <div class="form-group">
                <label for="Message">A message</label>
                <input type="text" name="Message" class="form-control" id="Message" placeholder="A messgage">
                <small class="form-text text-muted">16 characters max. No Special Characters</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button><br>
            <small class="form-text text-muted">The message will be automatically deleted after 30sec or when reaching 50.</small>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <div id="divMessages">
            
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>

Pages/Resultados.cshtml
@page
@model ResultadosModel
@{
    ViewData["Title"] = "John Deere Day";
}
@section Scripts {
    <script src="js/resultados.js"></script>
}
@section Styles {
    <link rel="stylesheet" href="css/resultados.css"/>
}


<div class="row">
    <div class="col-lg-6 text-center">
        <img src="images/JDLogo.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
    
    <div class="col-lg-6 text-center">
            <img src="images/ITS.png" width="300px" class="img-fluid" alt="Responsive image">
        </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <div id="divResults">
            
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullMessagePostingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Message Posting App - JD - ITS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FullMessagePostingApp
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/Trivia.cshtml
@page
@model TriviaModel
@{
    ViewData["Title"] = "John Deere Day";
}
@section Scripts {
    
}
@section Styles {
    
}


<div class="row">
    <div class="col-lg-6 text-center">
        <img src="images/JDLogo.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
    
    <div class="col-lg-6 text-center">
            <img src="images/ITS.png" width="300px" class="img-fluid" alt="Responsive image">
        </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-left">
        <h1>John Deere Day - ITS - Trivia</h1>
        <form method="post">
            <div class="form-group">
                <label for="inputTeam">Selecciona un equipo</label>
                <select id="inputTeam" asp-for="Equipo" class="form-control">
                    <option selected value="-1">...</option>
                    <option value="Equipo 1">Equipo 1</option>
                    <option value="Equipo 2">Equipo 2</option>
                    <option value="Equipo 3">Equipo 3</option>
                    <option value="Equipo 4">Equipo 4</option>
                    <option value="Equipo 5">Equipo 5</option>
                    <option value="Equipo 6">Equipo 6</option>
                    <option value="Equipo 7">Equipo 7</option>
                    <option value="Equipo 8">Equipo 8</option>
                    <option value="Equipo 9">Equipo 9</option>
                    <option value="Equipo 10">Equipo 10</option>
                </select>
            </div>
            
            @for (int j = 0; j < Model.TriviaItems.Count; j ++) {
                var item = Model.TriviaItems[j];
                <div class="form-group">
                    <label for="inputTeam">@Html.Raw(item.Question.Replace("\n", "<br>"))</label>
                    <input type="hidden" name="[@j].TriviaItemId" value="@item.Id"/>
                    <select id="inputTeam" name="[@j].Answer" class="form-control">
                        <option selected value="-1">...</option>
                        @for (int i = 0; i < item.Options.Length; i++) {
                            <option value="@i">@item.Options[i]</option>
                        }
                    </select>
                </div>
            }
            
            @if (!string.IsNullOrEmpty(Model.ErrorMessage)) {
                <div class="alert alert-danger" role="alert">
                    @Model.ErrorMessage
                </div>
            }

            <button type="submit" class="btn btn-primary">Submit</button><br>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <div id="divMessages">
            
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>